name: hestia
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Icons
  iconsax: ^0.0.8

  # Utility Packages
  http: 
  intl: ^0.18.1
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  path_provider: ^2.0.8
  fluttertoast: ^8.0.2
  shimmer: ^3.0.0
  image: ^3.0.1

  # State Management 
  get: ^4.6.5
  get_storage: ^2.1.1

  # Page Indicator
  smooth_page_indicator: ^1.1.0

  # Navigation Bar
  curved_navigation_bar: ^1.0.3

  # Read More
  readmore: ^2.2.0

  # Expandable Floating Button
  flutter_speed_dial: ^7.0.0

  # Text
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  stroke_text: any
  animated_text_kit: ^4.2.2

  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6

  # Google Maps
  google_maps_flutter: ^2.0.1
  location: ^5.0.3
  image_picker: ^1.0.5
  custom_info_window: ^1.0.1
  uuid: ^4.3.1  # used to get the id of the device
  geocoding: ^2.1.1
  google_geocoding_api: ^1.4.1
  widget_to_marker: ^1.0.4
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/authentication/
    - assets/images/gif/
    - assets/images/profile/
    - assets/images/background/
    - assets/map_style/
    - assets/icons/
   


  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

